### PR TITLE
Cleanup compilation warnings

### PR DESCRIPTION
**Pull request by tcm0116**

### CODE REVIEW

**Comment by tcm0116** [comment]
@thinkyhead I noticed this change isn't included when pulling this library down from PlatformIO. Do you have to do anything to push it to that repository for distribution?

**Comment by thinkyhead** [comment]
Does PlatformIO keep their own copy of the library for download? If not, then it should be configured to downloaded directly from [your `master` branch](https://github.com/MarlinFirmware/U8glib-HAL/tree/master).

**Comment by tcm0116** [comment]
I think it somehow has to be pushed to PlatformIO, but I'm not really sure
how it works. I just noticed that the warnings are still present in recent
Travis builds (along with a slew of new ones in very recent builds if
2.0.x).

**Comment by thinkyhead** [comment]
Sticking version numbers on the lib_deps in platformio.ini will keep them at bay.

**Pull request merged**
